Linking and Formatting
Anything-Minecraft-Team/anything-minecraft pull request #19
Opened 2021-01-26 18:01 UTC by mbround18

Contributions:

- Updated linking in sub files
- Fixed formatting, please use linting for consistency. 
- Added `.editorconfig`

2021-01-26 18:43 UTC, mbround18 commented
In the latest commit, I added a segment about PaperMC for 1.16+.

2021-01-26 21:22 UTC, JustDoom commented
Sorry but one of the other pull requests changed a file and won't let me merge, it's advanced jar picking

2021-01-26 22:48 UTC, mbround18 commented
@JustDoom fixed

2021-01-27 06:10 UTC, Silverarmor requested changes

2021-01-27 06:10 UTC, Silverarmor commented on .github/workflows/lint.yml
> +on: push
This should probably be
`on: [push. pull_request]`

2021-01-27 06:10 UTC, Silverarmor commented on tutorials/en_us/Advanced JAR picking.md
> +1. [Spigot](https://www.spigotmc.org/) - Original fork of Bukkit, improved performance vs CraftBukkit, still widely used, seems to be harder for newbies to download because it links to Jenkins,
Why use a numbered list here?
Also they probably shouldn't all be `1.`
Imo change to unordered list - using `-` dashes.

2021-01-27 06:10 UTC, Silverarmor commented on tutorials/en_us/Raspberry_pi_mcserver.md
> +### How to change RAM?
"change RAM"?

2021-01-27 06:10 UTC, Silverarmor commented on tutorials/en_us/Raspberry_pi_mcserver.md
> +### How to change RAM?
possibly "How to change allocated RAM" or similar

2021-01-27 06:11 UTC, JustDoom commented
so do i accept this?

2021-01-27 06:45 UTC, mbround18 commented
let me make some updates and fix merge conflicts

2021-01-27 06:51 UTC, mbround18 commented
@JustDoom updated

2021-01-27 07:26 UTC, Silverarmor approved these changes

2021-01-27 07:27 UTC, Kruemmelspalter commented
@mbround18 please resolve the conflicts

2021-01-27 07:28 UTC, mbround18 commented
lol im getting tired of resolving the same conflicts repetitively

2021-01-27 07:30 UTC, JustDoom commented
sorry about that

2021-01-27 07:34 UTC, mbround18 commented
I removed my changes in those files to avoid conflicts should other branches get merged.

2021-01-27 07:43 UTC, merged