resort files and folders
Anything-Minecraft-Team/anything-minecraft pull request #85
Opened 2021-03-18 01:53 UTC by JustDoom

# Description

draft for resorting the files and folders better, help/suggestions appreciated 

## Checklist

- [ ] My contributions follows the style guidelines of this project
- [ ] I have performed a self-review of my own contributions (checked for spelling errors, proper linking, etc)
- [ ] I have run linting on my branch before submitting the PR

2021-03-19 07:12 UTC, JustDoom commented
this might turn into a complete redo of the files, changing file locations and the text a bit

2021-05-03 04:29 UTC, JustDoom commented
oops, its nearly done but not yet

2021-05-10 03:22 UTC, JustDoom commented
this should be fine to merge, Ill fix the conflicts when I get home

2021-05-10 04:29 UTC, Silverarmor approved these changes

2021-05-10 14:50 UTC, Kruemmelspalter requested changes

2021-05-10 14:50 UTC, Kruemmelspalter commented on server/guides/other/SETUP.md
> +```sh
maybe use `bat` and not `sh` bc it's for a batch file

2021-05-10 14:50 UTC, Kruemmelspalter commented on server/guides/other/SETUP.md
> +--> `sudo apt install openjdk-xx-jre`
Maybe add either commands for other distros/ package managers or a note that not every distro uses `apt`

2021-05-10 14:50 UTC, Kruemmelspalter commented on server/guides/other/SETUP.md
> +- You can use an in-built linux utility called [tmux](https://github.com/tmux/tmux/wiki). Use this if the server is intended to be temporarily up.
It's not necessarily "in-built" bc on some (or most idk) you need to install it

2021-05-10 14:50 UTC, Kruemmelspalter commented on server/guides/other/SETUP.md
> +- You can register minecraft as a **system service**. Use this if the server is intended to be up 24/7 and requires automatic restarting in case of host shutdowns/failures.
For systemd, it's actually an `unit` and not a `service`

2021-05-10 14:50 UTC, Kruemmelspalter commented on server/guides/other/SETUP.md
> +`java -Xmx1024M -Xms1024M -jar server-jar nogui`
it's `server.jar` not `server-jar`

2021-05-10 14:50 UTC, Kruemmelspalter commented on server/guides/other/SETUP.md
> +#### You Build Docker
Maybe "Build it Yourself"

2021-05-10 14:50 UTC, Kruemmelspalter commented on server/guides/other/SETUP.md
> +
Maybe a reminder to use that in the directory with a server installed and maybe add an option to also copy the `world` folder etc.
For example just copy the whole folder

2021-05-10 14:50 UTC, Kruemmelspalter commented on server/guides/software/OPTIMIZATION.md
> +# OPtimization
O**p**timization

2021-05-10 14:50 UTC, Kruemmelspalter commented on server/guides/software/PICKING.md
> +# Choosing a software
Maybe not just "software" but "server software"

2021-05-12 06:13 UTC, Kruemmelspalter approved these changes

2021-05-12 06:14 UTC, merged